FROM golang:1.23.1-alpine

WORKDIR /app

# Install build essentials, Air, and dependencies
RUN apk add --no-cache \
    build-base \
    gcc \
    musl-dev \
    sqlite-dev \
    sqlite-libs && \
    go install github.com/air-verse/air@latest && \
    go mod download && \
    mkdir -p tmp frontend/templates internal/db

# Enable CGO
ENV CGO_ENABLED=1
ENV GOOS=linux

# Copy go mod files
COPY go.mod go.sum ./

# Copy .air.toml first
COPY .air.toml .

# Then copy the rest
COPY . .

# Run air with debug output
CMD ["air", "-d"]
