FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the binary
RUN apk add --no-cache gcc musl-dev sqlite-dev && \
    CGO_ENABLED=1 GOOS=linux go build -o main .

# Use a minimal alpine image for the final stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]