version: "3.8"

services:
  whoknows_go: # Changed from whoknows_flask
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: ghcr.io/who-knows-inc/whoknows_variations_server:latest
    env_file:
      - backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app # Changed path to match our Dockerfile.dev WORKDIR
      - ./frontend:/frontend # Add frontend volume for templates
    environment:
      - GO_ENV=development # Changed from FLASK_ENV
    networks:
      - my_network

  whoknows_nginx:
    build:
      context: ./network
      dockerfile: Dockerfile.nginx
    image: ghcr.io/who-knows-inc/whoknows_variations_nginx:latest
    ports:
      - "82:82"
    depends_on:
      - whoknows_go # Changed from whoknows_flask
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
