services:
  whoknows_go:
    image: ghcr.io/ukendt-gruppe/whoknows_server:latest
    env_file:
      - .env
    volumes:
      - ./frontend:/root/frontend
      - ./internal:/root/internal
    working_dir: /root
    ports:
      - "8080:8080"
    networks:
      - my_network

  whoknows_nginx:
    image: ghcr.io/ukendt-gruppe/whoknows_nginx:latest
    volumes:
      - ./frontend/static:/app/frontend/static
      - ./network/nginx.conf:/etc/nginx/nginx.conf:ro
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - metrics_logs:/var/log/metrics
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoknows_go
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # expose:
    #   - "9090"
    ports:
      - "9090:9090"
    depends_on:
      - whoknows_go
    networks:
      - my_network

  # grafana service
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SERVER_ROOT_URL=https://monitor.monkbusiness.dk/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  letsencrypt:
  certbot-www:
  metrics_logs:
  grafana_data: 
