version: '3.8'

services:
  whoknows_go:  
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: ghcr.io/ukendt-gruppe/whoknows_server:latest
    env_file:
      - backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app  
      - ./frontend:/frontend  
    environment:
      - GO_ENV=development  
    networks:
      - my_network

  whoknows_nginx:
    build:
      context: ./network
      dockerfile: Dockerfile
    image: ghcr.io/ukendt-gruppe/whoknows_nginx:latest
    ports:
      - "80:80"
    depends_on:
      - whoknows_go
    networks:
      - my_network

networks:
  my_network:
    driver: bridge