services:
  whoknows_go:
    image: ghcr.io/ukendt-gruppe/whoknows_server:latest
    env_file:
      - .env
    volumes:
      - ./frontend:/root/frontend
      - ./internal:/root/internal
    working_dir: /root
    networks:
      - my_network

  whoknows_nginx:
    image: ghcr.io/ukendt-gruppe/whoknows_nginx:latest
    volumes:
      - ./frontend/static:/app/frontend/static
      - ./network/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./network/nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoknows_go
    networks:
      - my_network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  my_network:
    driver: bridge