version: '3.8'

services:
  whoknows_go:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    ports:
      - "8080:8080"
    working_dir: /app
