services:
  whoknows_go:
    image: ghcr.io/ukendt-gruppe/whoknows_server:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    networks:
      - my_network

  whoknows_nginx:
    image: ghcr.io/ukendt-gruppe/whoknows_nginx:latest
    build:
      context: ./network
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoknows_go
    networks:
      - my_network
    volumes:
      - ./network/nginx.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - ./network/monitoring/collect_metrics.sh:/usr/local/bin/collect_metrics.sh
      - metrics_logs:/var/log/metrics

networks:
  my_network:
    driver: bridge

volumes:
  letsencrypt:
  certbot-www:
  metrics_logs: