services:
  whoknows_go:
    image: ghcr.io/ukendt-gruppe/whoknows_server:latest
    env_file:
      - .env
    volumes:
      - ./frontend:/root/frontend
      - ./internal:/root/internal
    working_dir: /root
    networks:
      - my_network

  whoknows_nginx:
    image: ghcr.io/ukendt-gruppe/whoknows_nginx:latest
    volumes:
      - ./frontend/static:/app/frontend/static
      - ./network/nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoknows_go
    networks:
      - my_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --email sifo0001@stud.kea.dk -d monkbusiness.dk --agree-tos --non-interactive

networks:
  my_network:
    driver: bridge