services:
  whoknows_go:
    image: ghcr.io/ukendt-gruppe/whoknows_server:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    networks:
      - my_network

  whoknows_nginx:
    image: ghcr.io/ukendt-gruppe/whoknows_nginx:latest
    build:
      context: ./network
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whoknows_go
    networks:
      - my_network
    volumes:
      - ./network/nginx-ssl.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email sifo0001@stud.kea.dk -d monkbusiness.dk --agree-tos --no-eff-email --force-renewal

networks:
  my_network:
    driver: bridge