definitions:
  handlers.AuthResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  handlers.RequestValidationError:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  handlers.SearchResponse:
    properties:
      data:
        items:
          additionalProperties: true
          type: object
        type: array
    type: object
  handlers.StandardResponse:
    properties:
      data:
        additionalProperties: true
        type: object
    type: object
info:
  contact: {}
paths:
  /api/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Log in a user with username and password.
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Log in a user
      tags:
      - auth
  /api/logout:
    get:
      description: Log out the current user and clear the session.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Log out a user
      tags:
      - auth
  /api/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register a new user with username, email, and password.
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Register a new user
      tags:
      - auth
  /api/search:
    get:
      consumes:
      - application/json
      description: Perform a search across pages and wiki_articles.
      parameters:
      - description: Search query
        in: query
        name: q
        required: true
        type: string
      - description: 'Language for search (default: en)'
        in: query
        name: language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SearchResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Search content
      tags:
      - search
  /api/weather:
    get:
      description: Fetch weather data for a specific location.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Get weather data
      tags:
      - weather
  /login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Log in a user by providing username and password.
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Log in a user
      tags:
      - auth
  /logout:
    get:
      description: Logs out the current user and clears the session.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Log out a user
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register a new user by providing username, email, and password.
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Register a new user
      tags:
      - auth
  /search:
    get:
      consumes:
      - application/json
      description: Search across pages and wiki articles using a query.
      parameters:
      - description: Search query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SearchResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Perform a search
      tags:
      - search
  /weather:
    get:
      description: Fetch weather data for a specific location.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RequestValidationError'
      summary: Get weather data
      tags:
      - weather
swagger: "2.0"
