name: Deploy to Azure VM
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
    - name: Copy repository to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_IP_ADDRESS }}
        username: azureuser
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/azureuser/whoKnows"
    - name: SSH and restart Go application on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP_ADDRESS }}
        username: azureuser
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        script: |
                  cd /home/azureuser/whoKnows/src/backend
                  # Remove the old binary if it exists
                  if [ -f whoknows ]; then
                    rm whoknows
                  fi
                  # Build the new binary
                  go build -o whoknows
                  # Ensure the new binary is executable
                  chmod +x whoknows
                  # Restart the service
                  sudo systemctl restart whoknows.service
                  # Print the file details for verification
                  ls -l whoknows
