name: Deploy to Azure VM
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
    - name: Copy repository to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_IP_ADDRESS }}
        username: azureuser
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/azureuser/whoKnows"
    - name: SSH and restart Go application on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP_ADDRESS }}
        username: azureuser
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        script: |
          # Enable error handling and print each command
          set -e
          set -x
          
          # Log current working directory
          echo "Current directory before change:"
          pwd

          # Navigate to the backend directory
          echo "Changing directory to /home/azureuser/whoKnows/src/backend"
          cd /home/azureuser/whoKnows/src/backend

          # Confirm directory change
          echo "Current directory after change:"
          pwd

          # Build the Go application and check for errors
          echo "Building Go application..."
          if go build -o whoknows; then
            echo "Go build succeeded."
          else
            echo "Go build failed!" >&2
            exit 1
          fi

          # Restart the Go application service
          echo "Restarting the whoknows.service"
          if sudo systemctl restart whoknows.service; then
            echo "Service restart succeeded."
          else
            echo "Service restart failed!" >&2
            exit 1
          fi

          # Log service status
          echo "Checking service status..."
          sudo systemctl status whoknows.service
