name: Development SSL Deployment

on:
  push:
    branches: [ feature/enablehttps ]
  workflow_dispatch:

env:
  CR_PAT: ${{ secrets.CR_PAT }}
  DOCKER_GITHUB_USERNAME: ${{ secrets.DOCKER_GITHUB_USERNAME }}
  SSH_USER: ${{ secrets.DEV_SSH_USER }}
  SSH_HOST: ${{ secrets.DEV_SSH_HOST }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ env.CR_PAT }} | docker login ghcr.io -u ${{ env.DOCKER_GITHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Images
        run: |
          cd src
          docker compose -f docker-compose.dev.deploy.yml build
          docker compose -f docker-compose.dev.deploy.yml push

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
          ssh-keyscan -H ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Dev Server
        run: |
          ssh -i ~/.ssh/ssh_key $SSH_USER@$SSH_HOST "
            mkdir -p ~/app/network &&
            rm -f ~/app/docker-compose.yml
          "
          
          scp -i ~/.ssh/ssh_key src/docker-compose.dev.deploy.yml $SSH_USER@$SSH_HOST:~/app/docker-compose.yml
          scp -i ~/.ssh/ssh_key src/network/nginx-ssl.dev.conf $SSH_USER@$SSH_HOST:~/app/network/

      - name: Start Services
        run: |
          ssh -i ~/.ssh/ssh_key $SSH_USER@$SSH_HOST "
            cd ~/app &&
            docker compose pull &&
            docker compose up -d
          "

      - name: Verify SSL Setup
        run: |
          echo "Waiting for services to start..."
          sleep 10
          
          echo "Checking HTTP redirect..."
          ssh -i ~/.ssh/ssh_key $SSH_USER@$SSH_HOST "
            curl -I -s http://localhost | grep -i 'location: https'
          "
          
          echo "Checking HTTPS connection..."
          ssh -i ~/.ssh/ssh_key $SSH_USER@$SSH_HOST "
            curl -k -I https://localhost | grep -i 'HTTP/1.1 200'
          "
          
          echo "Checking SSL certificate..."
          ssh -i ~/.ssh/ssh_key $SSH_USER@$SSH_HOST "
            echo | openssl s_client -connect localhost:443 2>/dev/null | openssl x509 -noout -text | grep 'Subject:'
          "
          
          echo "Checking container logs..."
          ssh -i ~/.ssh/ssh_key $SSH_USER@$SSH_HOST "
            docker compose logs
          "