name: OWASP Security Scan

on:
  push:
    branches: [ feature/owasp-sec-scan ]
  pull_request:
    branches: [ feature/owasp-sec-scan ]

permissions:
  contents: read
  issues: write
  security-events: write

jobs:
  owasp-zap:
    name: OWASP ZAP Full Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc musl-dev sqlite3
          go mod download
        working-directory: src/backend

      - name: Build application
        run: |
          CGO_ENABLED=1 GOOS=linux go build -o whoknows
        working-directory: src/backend

      - name: Start the application
        run: |
          ./whoknows &
          echo $! > ./pid.file
          sleep 10  # Give the application time to start
        working-directory: src/backend

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080'

      - name: Cleanup
        if: always()
        run: |
          if [ -f ./pid.file ]; then
            kill $(cat ./pid.file) || true
          fi
        working-directory: src/backend

  docker_scan:
    name: Docker Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build backend image
        run: |
          cd src/backend
          docker build -t backend:test -f Dockerfile.prod .

      - name: Run Trivy vulnerability scanner - Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'backend:test'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

      - name: Build nginx image
        run: |
          cd src/network
          docker build -t nginx:test -f Dockerfile.nginx .

      - name: Run Trivy vulnerability scanner - Nginx
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx:test'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

  dependency_check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'WhoKnows'
          path: 'src/backend'
          format: 'HTML'
          out: 'reports'

      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
