name: Unit Test and Coverage

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1' 
        
    - name: Install dependencies
      run: |
        cd src/backend/internal/handlers
        go mod download

    - name: Run tests with coverage
      run: |
        cd src/backend/handlers
        go test -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out

    - name: Generate coverage report
      run: |
        cd src/backend
        go tool cover -html=coverage.out -o coverage.html

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: src/backend/coverage.html

    - name: Display coverage percentage
      run: |
        cd src/backend
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
        echo "Total coverage: $COVERAGE"
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 44e7725b61d78d612fa0ee53b3437c78
        filename: go-coverage.json
        label: Coverage
        message: ${{ env.COVERAGE }}
        color: '#3C1'



