name: Unit Test and Coverage

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1' 
        
    - name: Install dependencies
      run: |
        cd src/backend
        go mod download

    - name: Run tests with coverage
      run: |
        cd src/backend/internal/handlers
        go test -v -coverprofile=coverage.out .
        go tool cover -func=coverage.out

    - name: Generate coverage report
      run: |
        cd src/backend/internal/handlers
        go tool cover -html=coverage.out -o coverage.html

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: src/backend/internal/handlers/coverage.html

    - name: Display coverage percentage
      run: |
        cd src/backend/internal/handlers
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
        echo "Total coverage: $COVERAGE"
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

    - name: Create Coverage Badge
      run: |
        COVERAGE=$(echo $COVERAGE | sed 's/%//')
        COLOR=$(awk -v cov="$COVERAGE" 'BEGIN { if (cov >= 80) print "brightgreen"; else if (cov >= 70) print "green"; else if (cov >= 60) print "yellowgreen"; else if (cov >= 50) print "yellow"; else if (cov >= 40) print "orange"; else print "red" }')
        JSON="{\"schemaVersion\": 1, \"label\": \"coverage\", \"message\": \"$COVERAGE%\", \"color\": \"$COLOR\"}"
        echo "$JSON" > coverage-badge.json
        gh gist edit 44e7725b61d78d612fa0ee53b3437c78 --add coverage-badge.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}