FROM nginx:latest

# Install certbot and its nginx plugin
RUN apt-get update && \
    apt-get install -y certbot python3-certbot-nginx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./ssl-init.sh /docker-entrypoint.d/ssl-init.sh

RUN chmod +x /docker-entrypoint.d/ssl-init.sh

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]